package org.javaturk.oopj.ch15;

import org.javaturk.oopj.ch14.domain.Employee;
import org.javaturk.oopj.ch15.domain.User;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * This is supposed to be an example fo leaky-abstraction.
 * Generated by ChatGPT: https://chat.openai.com/share/1094cabc-2c30-431f-a2eb-af908a5e7e31
 *
 */
public class ListAndSetExample {

    public static void main(String[] args) {

        User user1 = new User("Alice");
        User user2 = new User("Alice");

        List list = new ArrayList();
        list.add(user1);

        // The List.contains() method uses the equals() method for comparison
//        System.out.println("List contains user1: " + list.contains(user1)); // prints true
        System.out.println("List contains user2: " + list.contains(user2)); // prints false

        Set set = new HashSet();
        set.add(user1);
//        System.out.println("Set contains user1: " + set.contains(user1));
        System.out.println("Set contains user2: " + set.contains(user2));

    }
}
